### ISSUE TITLE
Create an alert with external link contains Splunk $results_link$

### ISSUE THREAD

**Issue by spacepatcher** [LetMeR00t/TA-thehive-cortex#42]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | thehiveproject/thehive4
| TheHive version / git hash   | 4.1.24-1

### Feature Description
Add a new alert action `external_link` to be able to set a link to the Splunk search alert job (from the Splunk `$results_link$` variable) as a setting in `savedsearches.conf`.

Thx!

**Comment by LetMeR00t** [comment]
Hello @spacepatcher  ,
Good news, a new version of this application with a complete rework is going to be ready soon.
Your issue will be fixed by this new version.
Tomorrow, I'll proceed with the commits/doc updates in the development branch. If you want to test it directly you can do so but of course I would recommand you to wait for the Splunk validation before.

**Comment by LetMeR00t** [comment]
Hi,
v3.0.0 with a fix for your issue is available.
I close this issue, thank you
