### ISSUE TITLE
[BUG] Error code 5 and 3

### ISSUE THREAD

**Issue by hsohsoler** [LetMeR00t/TA-thehive-cortex#56]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Oracle Linux Server release 6.10
| Addon version      | 2.3.1
| TheHive version / git hash   |  4.1.23-1

### Problem Description
Error 5 when send alert to thehive:
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/51417125/68ca987b-ea3f-46ce-a462-23406e7d3ff7)
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/51417125/e37351fa-6f33-4902-a1fa-1d01b8ad8f70)

I don't understand errors 3 and 5.

### Steps to Reproduce
1. Set alert
2. Set instance
3. Triger alert

### Possible Solutions
-

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
-

**Comment by LetMeR00t** [comment]
Hello
Error 3 is triggered if one param of your custom alert action has an issue (generally, a mandatory field is missing).
Error 5 means that my custom code for this application raised an exception somehow.
Can you check if you have any logs within the folder SPLUNK_HOME/var/log/Splunk relative to TheHive ? Sometimes it’s starting with thehive_ or with command_

Thank you

**Comment by hsohsoler** [comment]
![image](https://github.com/LetMeR00t/TA-thehive-cortex/assets/51417125/47293dcd-8e9a-470c-bdc1-e70ddd2be807)

**Comment by LetMeR00t** [comment]
Read the doc please:
This TA allows to add interaction features between [TheHive or Cortex (TheHive project)](https://thehive-project.org/) and Splunk. It allows to retrieve all cases/jobs information from TheHive/Cortex and to perform actions on these instances using Splunk, from a search or from a predefined dashboard. **All data types work with the exception of "file" because Splunk does not allow to send a file easily.**

I invite you to not use the datatype "file" and use something else instead

**Comment by hsohsoler** [comment]
Correct, The error was use fieldname as File datatype.

Thank you.
