### ISSUE TITLE
Two Questions related to bringing over an attachment and Custom Fields

### ISSUE THREAD

**Issue by cjharmening** [LetMeR00t/TA-thehive-cortex#82]
Hello,

Is there a way to bring over an attachment into theHive from Splunk. Say we have a saved search Report that has an output and want to bring that output of the .csv file over into thehive with the case?

Second, For custom fields to have a field from splunk come over into thehive alert as a custom field and not an observable we should just need to specify that in the thehive_datatypes csv correct? 

Thank you

**Comment by LetMeR00t** [comment]
Hello @cjharmening,

> Is there a way to bring over an attachment into theHive from Splunk. Say we have a saved search Report that has an output and want to bring that output of the .csv file over into thehive with the case?

It's an interesting feature. At the moment, no payload is available to be sent but we can think about it. Do you mean that it would be a "file" observable datatype that would be a CSV lookup ?

> Second, For custom fields to have a field from splunk come over into thehive alert as a custom field and not an observable we should just need to specify that in the thehive_datatypes csv correct?

For the custom fields, it depends on your app version but it's been a while (v3.0.0) since the custom fields are retrieved automatically from TheHive, meaning that if you define a custom field "hello_world" in TheHive and that you have a field named "hello_world" in your search results, it shall be automatically considered as a custom field.

**Comment by cjharmening** [comment]
Hello @LetMeR00t ,

Thank you for the fast response. I did figure out the Customfield part thank you. For the attachment what we are thinking is a saved report that runs daily that creates a csv file that we can export as an attachment. Kind of like how you can send an email and attach the report/ CSV via the adaptive response part.

Regards

**Comment by LetMeR00t** [comment]
Hello @cjharmening ,

So we are saying an attachment for an alert or case but not an observable with a "file" type right ?
If so, yes it should be possible and I'll work on it soon.

**Comment by LetMeR00t** [comment]
Hi @cjharmening,
The latest version in the "develop" branch has the feature you requested (attach splunk search results to a case or an alert). Would it be possible to test it on your side ?
Thank you
